.. _reference-programacion-python-django-problema_con_trror_that_port_is_already_in_use:

##############################################
Problema con Error That port is already in use
##############################################

.. code-block:: bash

    ps aux | grep -i manage
    kill -9 numero_pd
